### ISSUE TITLE
wrong profile

### ISSUE THREAD

**Issue by aurelbdx** [Seil0/cemu_UI#14]
Hi,

when I start a game, Cemu loads an old profile of this game.
However, I deleted all the profiles in C:\Program Files\cemu\gameProfiles

**Comment by Seil0** [comment]
can you provide me the app.log from _C:\Users\USERNAME\Documents\cemu_UI_ ?

**Comment by aurelbdx** [comment]
https://www.dropbox.com/s/vg7stqo9l2cfy51/app.log?dl=0

**Comment by Seil0** [comment]
From what i can see cemu_UI is working correctly. If you start cemu with `G: \ cemu \ Cemu.exe -f -g" F: \ [Jeux] \ [Emulateurs] \ [Wii U] \ Donkey Kong Country Tropical Freeze [ARKP01] \ code \ rs10_production.rpx " `from the cmd does the issue still appear?

**Comment by aurelbdx** [comment]
if I open Donkey Kong Country from the CMD or Cemu I have no issue.
But if I open this game from cemu_ui.jar, the issue still appear

**Comment by Seil0** [comment]
Are you sure you have the correct path  for cemu in cemu_UI since i don't see any way that cemu_UI could cause this issue and i'm currently unable to take further investigations.

**Comment by aurelbdx** [comment]
ok i'm conducting my investigation

**Comment by aurelbdx** [comment]
Same issue with another cemu instance in another path.
However, I have this issue only with Cemu v1.11.2 and v1.11.3.
No issue with v1.11.1 and below.

**Comment by aurelbdx** [comment]
I found another problem with v1.11.3.
I open cemu 1.11.3, I choose French in Console Language but Cemu stays in English if I open it from cemu_ui. I haven't this issue with v1.11.1.

**Comment by Seil0** [comment]
This is not a bug of cemu_UI (it's not even a bug in general). Due to the behavior of cemu to creat a new settings.bin etc. cemu_UI has it's own profileso you just need to copy the neede files to the cemu_UI.jar location or place the cemu_UI.jar into your cemu folder.

**Comment by aurelbdx** [comment]
Thanks :)
I have copy cemu_UI.jar into cemu folder and this solved my problem.
