### ISSUE TITLE
How to open?

### ISSUE THREAD

**Issue by Mortadolan** [Seil0/cemu_UI#2]
I tried double clicking it, using the CMD, using a .bat file, nothing worked, i have both the Oracle JRE and Oracle JDK installed, all i get is this error log.

[hs_err_pid8456.txt](https://github.com/Seil0/cemu_UI/files/907376/hs_err_pid8456.txt)

**Comment by Seil0** [comment]
to open it simply double click the .jar
@Mortadolan what's your gpu and graphics driver version?

**Comment by Mortadolan** [comment]
@Seil0 GTX 1060 and [381.65](http://www.nvidia.com/download/driverResults.aspx/117263/en-us)

**Comment by Seil0** [comment]
same issue as #1
