### ISSUE TITLE
Display issue with the last release

### ISSUE THREAD

**Issue by aurelbdx** [Seil0/cemu_UI#5]
Hi,

I have this problem at startup with the last release:
https://www.dropbox.com/s/0rm2lvj88q4tm7v/26-10-2017%2022-56-24.jpg?dl=0

**Comment by Seil0** [comment]
Resizing the window should temporarly fix this issue.

**Comment by aurelbdx** [comment]
yes I confirm

**Comment by Seil0** [comment]
I've uploaded a new build, which should fix this issue.
https://github.com/Seil0/cemu_UI/releases/tag/0.2.0

**Comment by aurelbdx** [comment]
Thanks. Now it's fixed!
